
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 09 14:25:26 CDT 2021
//----------------------------------------------------

package analizer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Operador_Suma = 12;
  public static final int Operador_Division = 15;
  public static final int Parentesis_c = 19;
  public static final int Out = 7;
  public static final int For = 8;
  public static final int Parentesis_a = 18;
  public static final int Numero = 24;
  public static final int Fun = 9;
  public static final int Operador_Multiplicacion = 14;
  public static final int ERROR = 25;
  public static final int Op_Separator = 22;
  public static final int Identificador = 23;
  public static final int Operador_Resta = 13;
  public static final int Llave_c = 21;
  public static final int Llave_a = 20;
  public static final int T_dato = 3;
  public static final int Operador_Igual = 11;
  public static final int In = 6;
  public static final int EOF = 0;
  public static final int If = 4;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int Op_Relacional = 17;
  public static final int Operador_Referencia = 10;
  public static final int While = 5;
  public static final int Operador_Modulo = 16;
}

